### ISSUE TITLE
希望在shutter工具中集成文字识别（OCR）的功能。

### ISSUE THREAD

**Issue by yimisunrise** [shutter-project/shutter#658] opened 2024-03-04 03:41 UTC
#### Description of requested feature:

I want to integrate text recognition (OCR) functionality into the shutter tool.
希望在shutter工具中集成文字识别（OCR）的功能。

#### Reasons for adding feature:

Most of the time, the screenshot use scenario is to extract the text content in the picture after capturing the picture.
很多时候的截图使用场景是需要截取图片后，提取图片中的文字内容。

#### Extra information, such as Shutter version, operating system and ideas for how to implement:

This function I think is more general.
该功能我认为是比较通用的。

**Comment by Photon89** [comment] 2024-03-04 05:12
That's a duplicate of our very first bug report: #1

**Closed as completed by Photon89** 2024-03-04 05:12 UTC
Labels: duplicate
