### ISSUE TITLE
Shutter not able to "Capture an area of the screen" any more Ubuntu 22.04

### ISSUE THREAD

**Issue by Alan72Dart** [shutter-project/shutter#635] opened 2023-11-22 02:06 UTC
#### Steps to reproduce the issue

1. Right click shutter icon
2. Select "Capture an area of the screen"
3. 

#### Error output
Can't take screenshots without X11 server

#### Extra information, such as Shutter version, display server in use (Xorg or Wayland), operating system and ideas for how to solve:
Ubuntu 22.04.3 LTS
GNOME 42.9
Wayland
This is a fresh install
Shutter worked for 3 days and then this problem happened

**Comment by Photon89** [comment] 2023-11-22 10:46
Hi, thanks for reporting the issue, this is a duplicate of #187. You can track any progress being made on it in that report.

**Closed as completed by Photon89** 2023-11-22 10:46 UTC
Labels: duplicate
