### ISSUE TITLE
Text tool font issue

### ISSUE THREAD

**Issue by ejazrasool** [shutter-project/shutter#394] opened 2021-08-12 23:34 UTC
#### Brief summary of issue
Default font not selected while using text tool

#### Steps to reproduce the issue

1. Take a screenshot
2. Open it in shutter default image editor
3. Select "A" text tool and click where on the image

#### Error output
The window that opens should have the default font selected but it has "None 0" for font family and font size respectively  

![2021-08-13--04-33-16](https://user-images.githubusercontent.com/4628021/129282912-af3b8355-3c90-4e73-b95c-d5f0de79648f.png)

#### Extra information, such as Shutter version, operating system and ideas for how to solve:
Uninstalled shutter version, deleted ~/.shutter and then reinstalled latest shutter version (0.98 rev 1570).
Using Ubuntu 20.04

I use shutter everyday for sending screenshots to design team, QA team and managers. This issue is turning out to be a huge time waster and source of annoyance. Every time I have to add text, I have to select the font and font size first. It used to be so good.
Please fix it.

**Comment by DarthGandalf** [comment] 2021-08-12 23:44
Dupe of #301

**Closed as completed by DarthGandalf** 2021-08-12 23:44 UTC
Labels: duplicate

**Comment by ejazrasool** [comment] 2021-08-13 01:37
ah I see.
