### ISSUE TITLE
shutter on Ubuntu 22.04 can not take screenshort with selection 

### ISSUE THREAD

**Issue by linuxmans** [shutter-project/shutter#495] opened 2022-08-09 08:29 UTC
#### Brief summary of issue
shutter on Ubuntu 22.04 can not take screenshot with selection 

button selection is disable can not click

**Comment by Photon89** [comment] 2022-08-09 09:02
You are using Wayland which has only rudimentary support so far, duplicate of https://github.com/shutter-project/shutter/issues/187.

**Closed as completed by Photon89** 2022-08-09 09:02 UTC
Labels: duplicate
