### ISSUE TITLE
External image file cannot be opened with Shutter

### ISSUE THREAD

**Issue by Photon89** [shutter-project/shutter#291] opened 2020-07-07 12:17 UTC
#### Brief summary of issue

When opening an image file with Shutter, the file isn't opened and the status line of Shutter reports that the file could not be opened.

#### Steps to reproduce the issue

1. Navigate to an image file with your file manager.
2. Right mouse button click on that file > Open with > Shutter
3. The Shutter window pops up but the image isn't added to the screenshots list.

#### Error output

Use of uninitialized value in concatenation (.) or string at /usr/sbin/shutter line 4005.
GLib-CRITICAL **: Source ID 201 was not found when attempting to remove it at /usr/sbin/shutter line 7014.

#### Extra information, such as Shutter version, operating system and ideas for how to solve:

Latest git commit (master branch), possibly introduced earlier already but worked with the latest release 0.94.3. 

Looks like the error messages only appear when trying to show an error message but the actual problem of not being able to access the file happens earlier but prints no error message. Possibly I am missing some GIO related dependency? If a bisection helps, I can do one.

**Comment by DarthGandalf** [comment] 2020-07-07 12:21
Hm, I can confirm that the file doesn't appear. But how do you get the error output when running shutter like that?

**Comment by Photon89** [comment] 2020-07-07 12:26
Right, good point, my reproduce steps were clearly incomplete. :smile: I just run Shutter from terminal and try to open the image while Shutter is already open.

**Comment by DarthGandalf** [comment] 2020-07-07 12:31
That doesn't work for me due to #272 (will be fixed though in the gtk3 branch if ever finished :) )

**Comment by DarthGandalf** [comment] 2020-07-07 12:39
> Latest git commit (master branch)

Please always specify the version

The moment there is any other commit to the master branch, the description will start lying.

**Comment by Photon89** [comment] 2020-07-07 13:03
Right, good point! Bug #272 should be easy to fix with this patch for perl-gtk2-unique: https://aur.archlinux.org/cgit/aur.git/tree/fix_segfault_2nd_instance.patch?h=perl-gtk2-unique

**Comment by DarthGandalf** [comment] 2020-07-07 19:51
```perl
$ Gnome2::VFS::URI->new('/tmp/foo.png')->to_string
file:///tmp/foo.png
$ Gnome2::VFS::URI->new('file:///tmp/foo.png')->to_string
file:///tmp/foo.png
```

This is why it worked before. Current GIO code doesn't attempt to parse a path as a URI

**Comment by Photon89** [comment] 2020-11-03 15:52
I just retested it and found that it is still broken if opening via

File > Open... 

from inside Shutter.

**Closed as completed** 2020-11-03 16:40 UTC
Labels: bug

**Comment by Photon89** [comment] 2020-11-03 17:09
Works, thanks!
