### ISSUE TITLE
Crash when start screenshot

### ISSUE THREAD

**Issue by STYNET** [shutter-project/shutter#322] opened 2021-04-27 15:05 UTC
#### Brief summary of issue

Install mode : 
sudo add-apt-repository ppa:linuxuprising/shutter
sudo apt-get update
sudo apt install shutter

I start application : 
shutter

I start area screenshot, and i have a bug on my 3 screens (the logo  shutter repeat on full screens) 
And no response, i must kill process.

#### Steps to reproduce the issue

1. start a screenshot
2. "crash"
3. kill process

#### Error output

fct_update_tray_menu was called by Gnome2::Wnck::Screen=HASH(0x55cff1b43080)

select was emitted by widget Gtk2::ToolButton=HASH(0x55cff28af8a8)
Using monitor: 1920 - 0 - 1920 - 1080

quit was emitted by widget 
GLib-CRITICAL **: Source ID 867 was not found when attempting to remove it at /usr/bin/shutter line 6984.

fct_update_tray_menu was called by Gnome2::Wnck::Screen=HASH(0x55cff1b43080)

quit was emitted by widget 
GLib-CRITICAL **: Source ID 8913 was not found when attempting to remove it at /usr/bin/shutter line 6984.

#### Extra information, such as Shutter version, operating system and ideas for how to solve:

Ubuntu 21.04 recent install

**Comment by Photon89** [comment] 2021-04-27 17:45
> (the logo shutter repeat on full screens)

Sounds like a duplicate of #187. Are you using Wayland?

**Comment by Photon89** [comment] 2021-06-10 15:54
Closing since OP didn't reply for over a month, also it is probably a duplicate of #187. Please comment if this is not the case.

**Closed as completed by Photon89** 2021-06-10 15:54 UTC
Labels: bug
