### ISSUE TITLE
Unable to close shutter on Ubuntu

### ISSUE THREAD

**Issue by jhonny-oliveira** [shutter-project/shutter#333] opened 2021-05-24 20:48 UTC
#### Brief summary of issue
Unable to close shutter from the window top right corner "X"

#### Steps to reproduce the issue

1. Run shutter in the terminal
2. Once it loads, click the window close button (X)
3. The process is still running and the command in terminal does not exit unless I hit CRTL-C

#### Error output
See attachment 
[ubuntu_hirsute-shutter_0.96.log](https://github.com/shutter-project/shutter/files/6534895/ubuntu_hirsute-shutter_0.96.log)

#### Extra information, such as Shutter version, operating system and ideas for how to solve:
Closing shutter via File > Quit exits the program as expected.
The result is similar in Ubuntu focal, groovy and hirsute. The log file is from hirsute. CRTL-C at line 2041.
I build the package with https://launchpad.net/~xtradeb/+archive/ubuntu/apps/+sourcefiles/shutter/0.96-1~xtradeb1/shutter_0.96-1~xtradeb1.debian.tar.xz . The remaining dependencies are also available in the associated PPA.

Thank you for your work!
Jhonny @ xtradeb

**Comment by Moonbase59** [comment] 2021-05-24 23:31
Probably just "closes" to the tray (which my version 0.94.3 does per default).
In my version, you can change this setting under *Edit → Preferences → Behaviour → Window Preferences → Minimize to tray when closing main window*.

**Comment by Photon89** [comment] 2021-05-25 05:13
Looks like a duplicate of https://github.com/shutter-project/shutter/issues/331 indeed.

**Comment by jhonny-oliveira** [comment] 2021-05-25 10:21
Hi!

You are totally correct, this is a duplicate of #331. I applied @DarthGandalf's patch and followed the @logix2's recommendations and I was able to workaround the problem. I will follow the original bug report for further developments.

Thank you!

**Comment by Photon89** [comment] 2021-05-25 10:26
Great, closing here then!

**Closed as completed by Photon89** 2021-05-25 10:26 UTC
Labels: bug, gtk3 regression

**Comment by DarthGandalf** [comment] 2021-05-30 16:24
While it's a duplicate, there was another important concern here: without the working tray, "close to tray" doesn't work as intended. This is also fixed now.
