### ISSUE TITLE
Shutter regularly crashes after capturing screens, especially at higher resolutions

### ISSUE THREAD

**Issue by kendoori** [shutter-project/shutter#339] opened 2021-05-28 16:23 UTC
#### Brief summary of issue
Shutter regularly crashes after capturing screens, especially at higher resolutions

#### Steps to reproduce the issue

1. Open Shutter and Select Desktop from interface
2. Capture will be invoked and then interface immediately shuts down

#### Error output
Below is captured when running Shutter from CLI

screenshot successfully saved to /home/kenny/Pictures/Workspace 1_185.png!
GLib-CRITICAL **: Source ID 365 was not found when attempting to remove it at /usr/bin/shutter line 7265.
Gdk-CRITICAL **: IA__gdk_window_get_events: assertion 'GDK_IS_WINDOW (window)' failed at /usr/bin/shutter line 2891.
Gdk-CRITICAL **: IA__gdk_window_set_events: assertion 'GDK_IS_WINDOW (window)' failed at /usr/bin/shutter line 2891.
The program 'shutter' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 8451 error_code 3 request_code 18 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

#### Extra information, such as Shutter version, operating system and ideas for how to solve:
Shutter 0.94.3, Linux Mint 20.1/Cinnamon

**Comment by Photon89** [comment] 2021-05-28 17:03
Such X errors are hard to catch and usually indicate some problem with the X configuration. Seems like a duplicate of https://github.com/shutter-project/shutter/issues/246, let's move further discussion there.

**Closed as completed by Photon89** 2021-05-28 17:03 UTC
Labels: bug
