### ISSUE TITLE
Error using Text or Autoincrement objects. 

### ISSUE THREAD

**Issue by vperetti** [shutter-project/shutter#342] opened 2021-05-31 14:21 UTC
#### Brief summary of issue
Error 

#### Steps to reproduce the issue

1. Take a screenshot
2. Edit
3. Insert a Text or autoincrement 

![image](https://user-images.githubusercontent.com/13136271/120206883-bd302a80-c1f9-11eb-8f0f-5f2a0a3d9a2e.png)

#### Error output
usr/bin/shutter line 6856.
 at /usr/bin/shutter line 6854.
	Shutter::App::fct_show_status_message(1, "/home/vinicius/shutter/Sele\x{e7}\x{e3}o_006.png aberto") called at /usr/bin/shutter line 5027
	Shutter::App::fct_open_files("file:///home/vinicius/shutter/Sele%C3%A7%C3%A3o_006.png") called at /usr/bin/shutter line 356
	Shutter::App::__ANON__(Glib::IO::SimpleAction=HASH(0x5632611efbe8), Glib::Variant=SCALAR(0x563261e321e8)) called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
	eval {...} called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
	Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x563260fc20e8)) called at /usr/bin/shutter line 10789

fct_update_tray_menu was called by Wnck::Screen=HASH(0x5632611ef7b0)

fct_update_tray_menu was called by Wnck::Screen=HASH(0x5632611ef7b0)

fct_update_tray_menu was called by Wnck::Screen=HASH(0x5632611ef7b0)

fct_update_tray_menu was called by Wnck::Screen=HASH(0x5632611ef7b0)
GLib-GObject-CRITICAL **: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 3191.
	eval {...} called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 3183
	Shutter::Draw::DrawingTool::set_and_save_drawing_properties(Shutter::Draw::DrawingTool=HASH(0x5632630eabd0), GooCanvas2::CanvasRect=HASH(0x563263618800), "") called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 5455
	Shutter::Draw::DrawingTool::event_item_on_button_release(Shutter::Draw::DrawingTool=HASH(0x5632630eabd0), GooCanvas2::CanvasImage=HASH(0x5632601ae770), GooCanvas2::CanvasImage=HASH(0x5632601ae770), Gtk3::Gdk::EventButton=SCALAR(0x563263618710)) called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 1843
	Shutter::Draw::DrawingTool::__ANON__(GooCanvas2::CanvasImage=HASH(0x5632601ae770), GooCanvas2::CanvasImage=HASH(0x5632601ae770), Gtk3::Gdk::EventButton=SCALAR(0x563263618710)) called at /usr/share/perl5/vendor_perl/Gtk3.pm line 572
	eval {...} called at /usr/share/perl5/vendor_perl/Gtk3.pm line 572
	Gtk3::main("Gtk3") called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 489
	Shutter::Draw::DrawingTool::show(Shutter::Draw::DrawingTool=HASH(0x5632630eabd0), "/home/vinicius/shutter/Sele\x{e7}\x{e3}o_006.png", "png", "image/png", "Sele\x{e7}\x{e3}o_006", "", HASH(0x56325f2279c8)) called at /usr/bin/shutter line 5782
	Shutter::App::fct_draw(Gtk3::ToolButton=HASH(0x5632615c8e38)) called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
	eval {...} called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
	Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x563260fc20e8)) called at /usr/bin/shutter line 10789
GLib-GObject-WARNING **: ../glib/gobject/gtype.c:4322: type id '0' is invalid at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 3191.
	eval {...} called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 3183
	Shutter::Draw::DrawingTool::set_and_save_drawing_properties(Shutter::Draw::DrawingTool=HASH(0x5632630eabd0), GooCanvas2::CanvasRect=HASH(0x563263618800), "") called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 5455
	Shutter::Draw::DrawingTool::event_item_on_button_release(Shutter::Draw::DrawingTool=HASH(0x5632630eabd0), GooCanvas2::CanvasImage=HASH(0x5632601ae770), GooCanvas2::CanvasImage=HASH(0x5632601ae770), Gtk3::Gdk::EventButton=SCALAR(0x563263618710)) called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 1843
	Shutter::Draw::DrawingTool::__ANON__(GooCanvas2::CanvasImage=HASH(0x5632601ae770), GooCanvas2::CanvasImage=HASH(0x5632601ae770), Gtk3::Gdk::EventButton=SCALAR(0x563263618710)) called at /usr/share/perl5/vendor_perl/Gtk3.pm line 572
	eval {...} called at /usr/share/perl5/vendor_perl/Gtk3.pm line 572
	Gtk3::main("Gtk3") called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 489
	Shutter::Draw::DrawingTool::show(Shutter::Draw::DrawingTool=HASH(0x5632630eabd0), "/home/vinicius/shutter/Sele\x{e7}\x{e3}o_006.png", "png", "image/png", "Sele\x{e7}\x{e3}o_006", "", HASH(0x56325f2279c8)) called at /usr/bin/shutter line 5782
	Shutter::App::fct_draw(Gtk3::ToolButton=HASH(0x5632615c8e38)) called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
	eval {...} called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
	Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x563260fc20e8)) called at /usr/bin/shutter line 10789
GLib-GObject-WARNING **: can't peek value table for type '<invalid>' which is not currently referenced at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 3191.
	eval {...} called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 3183
	Shutter::Draw::DrawingTool::set_and_save_drawing_properties(Shutter::Draw::DrawingTool=HASH(0x5632630eabd0), GooCanvas2::CanvasRect=HASH(0x563263618800), "") called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 5455
	Shutter::Draw::DrawingTool::event_item_on_button_release(Shutter::Draw::DrawingTool=HASH(0x5632630eabd0), GooCanvas2::CanvasImage=HASH(0x5632601ae770), GooCanvas2::CanvasImage=HASH(0x5632601ae770), Gtk3::Gdk::EventButton=SCALAR(0x563263618710)) called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 1843
	Shutter::Draw::DrawingTool::__ANON__(GooCanvas2::CanvasImage=HASH(0x5632601ae770), GooCanvas2::CanvasImage=HASH(0x5632601ae770), Gtk3::Gdk::EventButton=SCALAR(0x563263618710)) called at /usr/share/perl5/vendor_perl/Gtk3.pm line 572
	eval {...} called at /usr/share/perl5/vendor_perl/Gtk3.pm line 572
	Gtk3::main("Gtk3") called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 489
	Shutter::Draw::DrawingTool::show(Shutter::Draw::DrawingTool=HASH(0x5632630eabd0), "/home/vinicius/shutter/Sele\x{e7}\x{e3}o_006.png", "png", "image/png", "Sele\x{e7}\x{e3}o_006", "", HASH(0x56325f2279c8)) called at /usr/bin/shutter line 5782
	Shutter::App::fct_draw(Gtk3::ToolButton=HASH(0x5632615c8e38)) called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
	eval {...} called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
	Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x563260fc20e8)) called at /usr/bin/shutter line 10789
GLib-GObject-WARNING **: ../glib/gobject/gvalue.c:185: cannot initialize GValue with type '(null)', this type has no GTypeValueTable implementation at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 3191.
	eval {...} called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 3183
	Shutter::Draw::DrawingTool::set_and_save_drawing_properties(Shutter::Draw::DrawingTool=HASH(0x5632630eabd0), GooCanvas2::CanvasRect=HASH(0x563263618800), "") called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 5455
	Shutter::Draw::DrawingTool::event_item_on_button_release(Shutter::Draw::DrawingTool=HASH(0x5632630eabd0), GooCanvas2::CanvasImage=HASH(0x5632601ae770), GooCanvas2::CanvasImage=HASH(0x5632601ae770), Gtk3::Gdk::EventButton=SCALAR(0x563263618710)) called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 1843
	Shutter::Draw::DrawingTool::__ANON__(GooCanvas2::CanvasImage=HASH(0x5632601ae770), GooCanvas2::CanvasImage=HASH(0x5632601ae770), Gtk3::Gdk::EventButton=SCALAR(0x563263618710)) called at /usr/share/perl5/vendor_perl/Gtk3.pm line 572
	eval {...} called at /usr/share/perl5/vendor_perl/Gtk3.pm line 572
	Gtk3::main("Gtk3") called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 489
	Shutter::Draw::DrawingTool::show(Shutter::Draw::DrawingTool=HASH(0x5632630eabd0), "/home/vinicius/shutter/Sele\x{e7}\x{e3}o_006.png", "png", "image/png", "Sele\x{e7}\x{e3}o_006", "", HASH(0x56325f2279c8)) called at /usr/bin/shutter line 5782
	Shutter::App::fct_draw(Gtk3::ToolButton=HASH(0x5632615c8e38)) called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
	eval {...} called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
	Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x563260fc20e8)) called at /usr/bin/shutter line 10789
GLib-GObject-WARNING **: ../glib/gobject/gtype.c:4322: type id '0' is invalid at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 3191.
	eval {...} called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 3183
	Shutter::Draw::DrawingTool::set_and_save_drawing_properties(Shutter::Draw::DrawingTool=HASH(0x5632630eabd0), GooCanvas2::CanvasRect=HASH(0x563263618800), "") called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 5455
	Shutter::Draw::DrawingTool::event_item_on_button_release(Shutter::Draw::DrawingTool=HASH(0x5632630eabd0), GooCanvas2::CanvasImage=HASH(0x5632601ae770), GooCanvas2::CanvasImage=HASH(0x5632601ae770), Gtk3::Gdk::EventButton=SCALAR(0x563263618710)) called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 1843
	Shutter::Draw::DrawingTool::__ANON__(GooCanvas2::CanvasImage=HASH(0x5632601ae770), GooCanvas2::CanvasImage=HASH(0x5632601ae770), Gtk3::Gdk::EventButton=SCALAR(0x563263618710)) called at /usr/share/perl5/vendor_perl/Gtk3.pm line 572
	eval {...} called at /usr/share/perl5/vendor_perl/Gtk3.pm line 572
	Gtk3::main("Gtk3") called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 489
	Shutter::Draw::DrawingTool::show(Shutter::Draw::DrawingTool=HASH(0x5632630eabd0), "/home/vinicius/shutter/Sele\x{e7}\x{e3}o_006.png", "png", "image/png", "Sele\x{e7}\x{e3}o_006", "", HASH(0x56325f2279c8)) called at /usr/bin/shutter line 5782
	Shutter::App::fct_draw(Gtk3::ToolButton=HASH(0x5632615c8e38)) called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
	eval {...} called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
	Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x563260fc20e8)) called at /usr/bin/shutter line 10789
GLib-GObject-WARNING **: can't peek value table for type '<invalid>' which is not currently referenced at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 3191.
	eval {...} called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 3183
	Shutter::Draw::DrawingTool::set_and_save_drawing_properties(Shutter::Draw::DrawingTool=HASH(0x5632630eabd0), GooCanvas2::CanvasRect=HASH(0x563263618800), "") called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 5455
	Shutter::Draw::DrawingTool::event_item_on_button_release(Shutter::Draw::DrawingTool=HASH(0x5632630eabd0), GooCanvas2::CanvasImage=HASH(0x5632601ae770), GooCanvas2::CanvasImage=HASH(0x5632601ae770), Gtk3::Gdk::EventButton=SCALAR(0x563263618710)) called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 1843
	Shutter::Draw::DrawingTool::__ANON__(GooCanvas2::CanvasImage=HASH(0x5632601ae770), GooCanvas2::CanvasImage=HASH(0x5632601ae770), Gtk3::Gdk::EventButton=SCALAR(0x563263618710)) called at /usr/share/perl5/vendor_perl/Gtk3.pm line 572
	eval {...} called at /usr/share/perl5/vendor_perl/Gtk3.pm line 572
	Gtk3::main("Gtk3") called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 489
	Shutter::Draw::DrawingTool::show(Shutter::Draw::DrawingTool=HASH(0x5632630eabd0), "/home/vinicius/shutter/Sele\x{e7}\x{e3}o_006.png", "png", "image/png", "Sele\x{e7}\x{e3}o_006", "", HASH(0x56325f2279c8)) called at /usr/bin/shutter line 5782
	Shutter::App::fct_draw(Gtk3::ToolButton=HASH(0x5632615c8e38)) called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
	eval {...} called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
	Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x563260fc20e8)) called at /usr/bin/shutter line 10789
Falha de segmentação (imagem do núcleo gravada)

#### Extra information, such as Shutter version, operating system and ideas for how to solve:
Shutter 0.96 Rev.1547 Archlinux.

**Comment by DarthGandalf** [comment] 2021-05-31 15:12
Duplicate of #332

**Closed as completed by DarthGandalf** 2021-05-31 15:12 UTC
Labels: bug, gtk3 regression
