### ISSUE TITLE
Iregular behavior of the profiles system

### ISSUE THREAD

**Issue by fico-LK** [shutter-project/shutter#461] opened 2022-04-03 22:29 UTC
During a Shutter session is possible to add a new profile or more than one in the preferences dialog. The profile/s It is saved as expected in the users .shutter configuration  folder.
But restarting the application it does not read the available profiles except the default  ( *.xml and *_accounts.xm.).
The profiles (.xml files) are there. But they seem to be ignored
I titled this issue 'Irregular behavior'  because in very rare occasions it was able to read them.
Using the profiles to adjust different destination/save directories and name-formating , improves significantly the working performance
Many thanks for such a great tool!!

**Steps to reproduce the issue**

1. Add one or two profiles using the preference dialog ( main tab)
2. Close the application
3. Restart the application
4. Profiles are present in the .shutter users folder but do not show in available profiles  in the preference dialog

Using OS Linux-Mint v:20 Ulyana
**Shutter version** 0.99.2 , Revision 1523

FLK

**Comment by Photon89** [comment] 2022-04-04 04:12
That's a dupe of #453. Thanks for your report though!

**Closed as completed by Photon89** 2022-04-04 04:12 UTC
Labels: duplicate
