### ISSUE TITLE
Crashes when trying to add text in editor

### ISSUE THREAD

**Issue by egbuk** [shutter-project/shutter#378] opened 2021-08-03 07:42 UTC
#### Brief summary of issue

Can't add text to screenshot, crashes after text tool select when trying to apply

#### Steps to reproduce the issue

1. Take a screenshot/open picture
2. Go to edit mode
3. Click on letter icon, "add some text to screenshot"
4. Click on any point on image surface, application crashes

#### Error output
`GLib-GObject-CRITICAL **: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 3218.
        eval {...} called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 3210
        Shutter::Draw::DrawingTool::set_and_save_drawing_properties(Shutter::Draw::DrawingTool=HASH(0x55c4f6c7d5e8), GooCanvas2::CanvasRect=HASH(0x55c4fb1bc378), "") called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 5455
        Shutter::Draw::DrawingTool::event_item_on_button_release(Shutter::Draw::DrawingTool=HASH(0x55c4f6c7d5e8), GooCanvas2::CanvasImage=HASH(0x55c4f86e3e80), GooCanvas2::CanvasImage=HASH(0x55c4f86e3e80), Gtk3::Gdk::EventButton=SCALAR(0x55c4fb062990)) called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 1843
        Shutter::Draw::DrawingTool::__ANON__(GooCanvas2::CanvasImage=HASH(0x55c4f86e3e80), GooCanvas2::CanvasImage=HASH(0x55c4f86e3e80), Gtk3::Gdk::EventButton=SCALAR(0x55c4fb062990)) called at /usr/share/perl5/vendor_perl/Gtk3.pm line 572
        eval {...} called at /usr/share/perl5/vendor_perl/Gtk3.pm line 572
        Gtk3::main("Gtk3") called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 489
        Shutter::Draw::DrawingTool::show(Shutter::Draw::DrawingTool=HASH(0x55c4f6c7d5e8), "/home/egor/Pictures/Screenshots/Selection_1618.png", "png", "image/png", "Selection_1618", "", HASH(0x55c4f7c0f198)) called at /usr/bin/shutter line 5782
        Shutter::App::fct_draw(Gtk3::ToolButton=HASH(0x55c4f97dd148)) called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
        eval {...} called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
        Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x55c4f8ed5570)) called at /usr/bin/shutter line 10789
GLib-GObject-WARNING **: ../glib/gobject/gtype.c:4322: type id '0' is invalid at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 3218.
        eval {...} called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 3210
        Shutter::Draw::DrawingTool::set_and_save_drawing_properties(Shutter::Draw::DrawingTool=HASH(0x55c4f6c7d5e8), GooCanvas2::CanvasRect=HASH(0x55c4fb1bc378), "") called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 5455
        Shutter::Draw::DrawingTool::event_item_on_button_release(Shutter::Draw::DrawingTool=HASH(0x55c4f6c7d5e8), GooCanvas2::CanvasImage=HASH(0x55c4f86e3e80), GooCanvas2::CanvasImage=HASH(0x55c4f86e3e80), Gtk3::Gdk::EventButton=SCALAR(0x55c4fb062990)) called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 1843
        Shutter::Draw::DrawingTool::__ANON__(GooCanvas2::CanvasImage=HASH(0x55c4f86e3e80), GooCanvas2::CanvasImage=HASH(0x55c4f86e3e80), Gtk3::Gdk::EventButton=SCALAR(0x55c4fb062990)) called at /usr/share/perl5/vendor_perl/Gtk3.pm line 572
        eval {...} called at /usr/share/perl5/vendor_perl/Gtk3.pm line 572
        Gtk3::main("Gtk3") called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 489
        Shutter::Draw::DrawingTool::show(Shutter::Draw::DrawingTool=HASH(0x55c4f6c7d5e8), "/home/egor/Pictures/Screenshots/Selection_1618.png", "png", "image/png", "Selection_1618", "", HASH(0x55c4f7c0f198)) called at /usr/bin/shutter line 5782
        Shutter::App::fct_draw(Gtk3::ToolButton=HASH(0x55c4f97dd148)) called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
        eval {...} called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
        Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x55c4f8ed5570)) called at /usr/bin/shutter line 10789
GLib-GObject-WARNING **: can't peek value table for type '<invalid>' which is not currently referenced at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 3218.
        eval {...} called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 3210
        Shutter::Draw::DrawingTool::set_and_save_drawing_properties(Shutter::Draw::DrawingTool=HASH(0x55c4f6c7d5e8), GooCanvas2::CanvasRect=HASH(0x55c4fb1bc378), "") called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 5455
        Shutter::Draw::DrawingTool::event_item_on_button_release(Shutter::Draw::DrawingTool=HASH(0x55c4f6c7d5e8), GooCanvas2::CanvasImage=HASH(0x55c4f86e3e80), GooCanvas2::CanvasImage=HASH(0x55c4f86e3e80), Gtk3::Gdk::EventButton=SCALAR(0x55c4fb062990)) called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 1843
        Shutter::Draw::DrawingTool::__ANON__(GooCanvas2::CanvasImage=HASH(0x55c4f86e3e80), GooCanvas2::CanvasImage=HASH(0x55c4f86e3e80), Gtk3::Gdk::EventButton=SCALAR(0x55c4fb062990)) called at /usr/share/perl5/vendor_perl/Gtk3.pm line 572
        eval {...} called at /usr/share/perl5/vendor_perl/Gtk3.pm line 572
        Gtk3::main("Gtk3") called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 489
        Shutter::Draw::DrawingTool::show(Shutter::Draw::DrawingTool=HASH(0x55c4f6c7d5e8), "/home/egor/Pictures/Screenshots/Selection_1618.png", "png", "image/png", "Selection_1618", "", HASH(0x55c4f7c0f198)) called at /usr/bin/shutter line 5782
        Shutter::App::fct_draw(Gtk3::ToolButton=HASH(0x55c4f97dd148)) called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
        eval {...} called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
        Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x55c4f8ed5570)) called at /usr/bin/shutter line 10789
GLib-GObject-WARNING **: ../glib/gobject/gvalue.c:185: cannot initialize GValue with type '(null)', this type has no GTypeValueTable implementation at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 3218.
        eval {...} called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 3210
        Shutter::Draw::DrawingTool::set_and_save_drawing_properties(Shutter::Draw::DrawingTool=HASH(0x55c4f6c7d5e8), GooCanvas2::CanvasRect=HASH(0x55c4fb1bc378), "") called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 5455
        Shutter::Draw::DrawingTool::event_item_on_button_release(Shutter::Draw::DrawingTool=HASH(0x55c4f6c7d5e8), GooCanvas2::CanvasImage=HASH(0x55c4f86e3e80), GooCanvas2::CanvasImage=HASH(0x55c4f86e3e80), Gtk3::Gdk::EventButton=SCALAR(0x55c4fb062990)) called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 1843
        Shutter::Draw::DrawingTool::__ANON__(GooCanvas2::CanvasImage=HASH(0x55c4f86e3e80), GooCanvas2::CanvasImage=HASH(0x55c4f86e3e80), Gtk3::Gdk::EventButton=SCALAR(0x55c4fb062990)) called at /usr/share/perl5/vendor_perl/Gtk3.pm line 572
        eval {...} called at /usr/share/perl5/vendor_perl/Gtk3.pm line 572
        Gtk3::main("Gtk3") called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 489
        Shutter::Draw::DrawingTool::show(Shutter::Draw::DrawingTool=HASH(0x55c4f6c7d5e8), "/home/egor/Pictures/Screenshots/Selection_1618.png", "png", "image/png", "Selection_1618", "", HASH(0x55c4f7c0f198)) called at /usr/bin/shutter line 5782
        Shutter::App::fct_draw(Gtk3::ToolButton=HASH(0x55c4f97dd148)) called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
        eval {...} called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
        Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x55c4f8ed5570)) called at /usr/bin/shutter line 10789
GLib-GObject-WARNING **: ../glib/gobject/gtype.c:4322: type id '0' is invalid at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 3218.
        eval {...} called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 3210
        Shutter::Draw::DrawingTool::set_and_save_drawing_properties(Shutter::Draw::DrawingTool=HASH(0x55c4f6c7d5e8), GooCanvas2::CanvasRect=HASH(0x55c4fb1bc378), "") called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 5455
        Shutter::Draw::DrawingTool::event_item_on_button_release(Shutter::Draw::DrawingTool=HASH(0x55c4f6c7d5e8), GooCanvas2::CanvasImage=HASH(0x55c4f86e3e80), GooCanvas2::CanvasImage=HASH(0x55c4f86e3e80), Gtk3::Gdk::EventButton=SCALAR(0x55c4fb062990)) called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 1843
        Shutter::Draw::DrawingTool::__ANON__(GooCanvas2::CanvasImage=HASH(0x55c4f86e3e80), GooCanvas2::CanvasImage=HASH(0x55c4f86e3e80), Gtk3::Gdk::EventButton=SCALAR(0x55c4fb062990)) called at /usr/share/perl5/vendor_perl/Gtk3.pm line 572
        eval {...} called at /usr/share/perl5/vendor_perl/Gtk3.pm line 572
        Gtk3::main("Gtk3") called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 489
        Shutter::Draw::DrawingTool::show(Shutter::Draw::DrawingTool=HASH(0x55c4f6c7d5e8), "/home/egor/Pictures/Screenshots/Selection_1618.png", "png", "image/png", "Selection_1618", "", HASH(0x55c4f7c0f198)) called at /usr/bin/shutter line 5782
        Shutter::App::fct_draw(Gtk3::ToolButton=HASH(0x55c4f97dd148)) called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
        eval {...} called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
        Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x55c4f8ed5570)) called at /usr/bin/shutter line 10789
GLib-GObject-WARNING **: can't peek value table for type '<invalid>' which is not currently referenced at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 3218.
        eval {...} called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 3210
        Shutter::Draw::DrawingTool::set_and_save_drawing_properties(Shutter::Draw::DrawingTool=HASH(0x55c4f6c7d5e8), GooCanvas2::CanvasRect=HASH(0x55c4fb1bc378), "") called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 5455
        Shutter::Draw::DrawingTool::event_item_on_button_release(Shutter::Draw::DrawingTool=HASH(0x55c4f6c7d5e8), GooCanvas2::CanvasImage=HASH(0x55c4f86e3e80), GooCanvas2::CanvasImage=HASH(0x55c4f86e3e80), Gtk3::Gdk::EventButton=SCALAR(0x55c4fb062990)) called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 1843
        Shutter::Draw::DrawingTool::__ANON__(GooCanvas2::CanvasImage=HASH(0x55c4f86e3e80), GooCanvas2::CanvasImage=HASH(0x55c4f86e3e80), Gtk3::Gdk::EventButton=SCALAR(0x55c4fb062990)) called at /usr/share/perl5/vendor_perl/Gtk3.pm line 572
        eval {...} called at /usr/share/perl5/vendor_perl/Gtk3.pm line 572
        Gtk3::main("Gtk3") called at /usr/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 489
        Shutter::Draw::DrawingTool::show(Shutter::Draw::DrawingTool=HASH(0x55c4f6c7d5e8), "/home/egor/Pictures/Screenshots/Selection_1618.png", "png", "image/png", "Selection_1618", "", HASH(0x55c4f7c0f198)) called at /usr/bin/shutter line 5782
        Shutter::App::fct_draw(Gtk3::ToolButton=HASH(0x55c4f97dd148)) called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
        eval {...} called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
        Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x55c4f8ed5570)) called at /usr/bin/shutter line 10789
fish: Job 1, 'shutter' terminated by signal SIGSEGV (Address boundary error)`

#### Extra information, such as Shutter version, operating system and ideas for how to solve:
Shutter 0.96 Rev.1547, perl v5.34.0 x86_64-linux-thread-multi, Manjaro 21.1.0 Pahvo, kernel: x86_64 Linux 5.13.5-1-MANJARO

**Comment by Photon89** [comment] 2021-08-03 07:49
This is fixed in 0.97 which is in Manjaro's repos for quite some time already, please update your system!

Closing as duplicate of https://github.com/shutter-project/shutter/issues/342

**Closed as completed by Photon89** 2021-08-03 07:49 UTC
Labels: bug
