### ISSUE TITLE
How do i take a screenshot?

### ISSUE THREAD

**Issue by MSkill1** [shutter-project/shutter#632] opened 2023-10-30 11:20 UTC

**Comment by Photon89** [comment] 2023-10-30 11:25
Basically, you start Shutter and press the button for the corresponding capture mode. Please be more specific if you want to get a more detailed answer!

**Comment by MSkill1** [comment] 2023-10-30 11:45
sorry! didn't realize it would post that - using a different app to take the shot - everything except the whole desktop option is grayed out:

[image.png]

------- Original Message -------

**Comment by Photon89** [comment] 2023-10-30 11:55
You are probably using Wayland, which is not fully supported yet. For now your only option is to switch back to Xorg (you can do so in the login dialog). Some code changes are being worked on to enable at least the selection mode for Wayland but nothing is finished yet: #612

**Comment by MSkill1** [comment] 2023-10-30 13:57
Got it - thanks for the help!

best,
Matt

------- Original Message -------

**Comment by Photon89** [comment] 2023-10-30 14:01
You're welcome! :smiley: Closing as duplicate of #187.

**Closed as completed by Photon89** 2023-10-30 14:01 UTC
Labels: duplicate
