### ISSUE TITLE
Error saving screenshot - Filename too long

### ISSUE THREAD

**Issue by Photon89** [shutter-project/shutter#216] opened 2020-06-11 16:56 UTC
The issue is best described by screenshot which is attached

current version from ubuntu 16.10 - aka shutter 0.93.1 Rev.1278

There was an error saving the image to '/home/ligi/Pictures/'.

Error while saving the image 'PassbookForAndroid - [~-git-PassbookForAndroid] - [android] - ~-git-PassbookForAndroid-android-src-main-java-org-ligi-passandroid-ui-PassAdapter.kt - Android Studio 2.2.3_007.png'.

------

steps to reproduce

#1 open shutter
#2 click on window screenshot button
#3 select window with long title

Launchpad Details: [#LP1649864](https://bugs.launchpad.net/bugs/1649864) ligi - 2016-12-14 11:38:58 +0000

**Comment by Photon89** [comment] 2020-06-11 16:56
Attachment: [shutterbug.png](https://api.launchpad.net/1.0/shutter/+bug/1649864/+attachment/4791515/data)



Launchpad Details: [#LPC](https://bugs.launchpad.net/shutter/+bug/1649864/comments/1) ligi - 2016-12-14 11:38:58 +0000

**Comment by Mingun** [comment] 2021-07-23 07:28
Duplicate of #204

**Closed as completed** 2021-07-23 07:57 UTC
