### ISSUE TITLE
Shutter 0.97 Cannot move a selection

### ISSUE THREAD

**Issue by philgarratt55** [shutter-project/shutter#375] opened 2021-07-30 13:54 UTC
I cannot work out how to move a selection in Shutter 0.97.  I could do it in previous versions, but I cannot find a way to drag a selection.  I've tried all combinations of Alt, Ctrl and Shift with the mouse buttons, but it always starts a new selection.  Thanks for any advice.

**Comment by DarthGandalf** [comment] 2021-07-30 14:25
Dupe of #350

**Closed as completed by DarthGandalf** 2021-07-30 14:25 UTC
Labels: question
