### ISSUE TITLE
Edit "pixelize" is insecure

### ISSUE THREAD

**Issue by matthias-ccri** [shutter-project/shutter#624] opened 2023-10-04 22:01 UTC
Pixelize draws semi-transparent pixels at the edges, which don't completely obscure the contents. See below.

Pixelized image created by Shutter's Edit feature.
![image](https://github.com/shutter-project/shutter/assets/18034092/917fe8b4-5164-49db-9eb7-cf8e5c7bb25f)

With color levels adjusted:  
![image](https://github.com/shutter-project/shutter/assets/18034092/b26a2a6a-48f3-4347-b15a-beb8fceaed2e)

Users may not notice this, so they may unwittingly expose sensitive information thinking it's properly masked.

**Pixelize should not output any transparency.**

**Comment by Photon89** [comment] 2023-10-05 03:57
Thanks for reporting this issue, this is a duplicate of #226 though.

**Closed as completed by Photon89** 2023-10-05 03:57 UTC
Labels: duplicate

**Comment by limitedAtonement** [comment] 2025-02-11 10:59
> ...this is a duplicate of #226 though.

Which is a duplicate of #218.
