### ISSUE TITLE
After Updating the Application Double Click not working (Ubuntu 20.04)

### ISSUE THREAD

**Issue by salman9997** [shutter-project/shutter#360] opened 2021-07-08 05:19 UTC
#### Brief summary of issue

On selection, the screen double clicks not working. It shows a + icon on the screen. It works properly on press Enter key.
It was working fine before updating.

**Steps to reproduce the issue**

1. Launch the selection mode
2. Select an area to take a screenshot
3. Try to initiate the screenshot with a DoubleClick

#### Error output
Nothing specific.

#### Extra information, such as Shutter version, operating system, and ideas for how to solve:
Version 0.97

**Comment by Photon89** [comment] 2021-07-08 07:06
Duplicate of #359, right on top of the list. ;)

**Closed as completed by Photon89** 2021-07-08 07:06 UTC
Labels: bug
