### ISSUE TITLE
X11 | Critical errors reported while starting the application

### ISSUE THREAD

**Issue by Ricky-Tigg** [shutter-project/shutter#427] opened 2021-11-11 12:45 UTC
_version_: 0.99.2; _installed from_: Fedora 35 repository; _Tested in_: Gnome 41.

On both Wayland and X11, Shutter can be launched. However critical errors are reported in terminal while starting the application, then closing it. Here are these outputs in X11: [shutter_x11_output_redirected.txt](https://github.com/shutter-project/shutter/files/7520440/shutter_x11_output_redirected.txt), [shutter_x11_output_non-redirected.txt](https://github.com/shutter-project/shutter/files/7520444/shutter_x11_output_non-redirected.txt)

**Comment by Photon89** [comment] 2021-11-11 12:47
As far as I can see, the errors can be ignored, looks like a duplicate of https://github.com/shutter-project/shutter/issues/338

**Closed as completed** 2022-03-06 14:55 UTC
Labels: duplicate
