### ISSUE TITLE
Query on gnome-web-photo

### ISSUE THREAD

**Issue by wizardfromoz57** [shutter-project/shutter#615] opened 2023-08-26 06:58 UTC
#### Shutter version, 0.99.2-4

Thanks

Chris Turner
wizardfromoz
I am an administrator at linux.org

**Comment by Photon89** [comment] 2023-08-26 07:18
Yes, this is a known issue: https://github.com/shutter-project/shutter/issues/285 We were considering to switch from gnome-web-photo to `wkhtmltoimage` or `weasyprint` but had security concerns (please read the discussion in the last few comments of above issue report).

**Comment by Photon89** [comment] 2024-04-07 07:18
Closing as duplicate of #285. Please comment there if there are further open questions!

**Closed as completed by Photon89** 2024-04-07 07:18 UTC
Labels: enhancement
